# Generated by Django 5.0 on 2025-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='users_addr_user_default_idx',
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='users_city_state_idx',
        ),
        migrations.RemoveIndex(
            model_name='postalcode',
            name='users_postal_city_idx',
        ),
        migrations.RemoveIndex(
            model_name='postalcode',
            name='users_postal_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='state',
            name='users_state_country_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_type_status_idx',
        ),
    ]
