# Generated by Django 5.0 on 2025-12-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.city'),
        ),
        migrations.AddField(
            model_name='materialsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterial',
            unique_together={('material_name', 'material_type')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacturingspecification',
            unique_together={('variant_size', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='materialsupplier',
            unique_together={('material', 'supplier')},
        ),
    ]
