# Generated by Django 5.0 on 2025-12-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
