# Generated by Django 5.0 on 2025-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='manufacturingspecification',
            name='mfg_spec_vs_idx',
        ),
        migrations.RemoveIndex(
            model_name='manufacturingspecification',
            name='mfg_spec_mat_idx',
        ),
        migrations.RemoveIndex(
            model_name='manufacturingspecification',
            name='mfg_spec_vs_mat_idx',
        ),
        migrations.RemoveIndex(
            model_name='materialsupplier',
            name='mfg_ms_mat_sup_idx',
        ),
        migrations.RemoveIndex(
            model_name='materialsupplier',
            name='mfg_ms_preferred_idx',
        ),
        migrations.RemoveIndex(
            model_name='materialsupplier',
            name='mfg_ms_mat_pref_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawmaterial',
            name='mfg_rm_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawmaterial',
            name='mfg_rm_qty_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawmaterial',
            name='mfg_rm_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='rawmaterial',
            name='mfg_rm_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='mfg_sup_name_idx',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='default_reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default minimum stock level for reorder alerts', max_digits=10, null=True),
        ),
    ]
