# Generated by Django 5.0 on 2025-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='orders_cart_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='orders_cart_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='orders_ci_cart_vs_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_ord_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_ord_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_ord_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_oi_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_oi_vs_idx',
        ),
    ]
