# Generated by Django 5.0 on 2025-12-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='taxconfiguration',
            unique_together={('tax_name', 'effective_from')},
        ),
    ]
