# Generated by Django 5.0 on 2025-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='finance_inv_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_ord_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_rz_ord_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxconfiguration',
            name='finance_tax_eff_from_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxconfiguration',
            name='finance_tax_active_idx',
        ),
    ]
