# Generated by Django 5.0 on 2025-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='complaint',
            name='support_cmp_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='complaint',
            name='support_cmp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='complaint',
            name='support_cmp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='complaint',
            name='support_cmp_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='support_fb_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='support_fb_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='support_fb_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedback',
            name='support_fb_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='inquiry',
            name='support_inq_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='inquiry',
            name='support_inq_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='inquiry',
            name='support_inq_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationprice',
            name='support_qp_quot_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationprice',
            name='support_qp_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationprice',
            name='support_qp_valid_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationrequest',
            name='support_qr_inquiry_idx',
        ),
        migrations.RemoveIndex(
            model_name='quotationrequest',
            name='support_qr_status_idx',
        ),
    ]
