# Generated by Django 5.0 on 2025-12-18 10:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_complaint_support_cmp_user_status_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='logo_file_url',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='logo_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
