# Generated by Django 6.0.2 on 2026-02-26 07:14

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cancellation_reason_order_cancelled_at_and_more'),
        ('support', '0006_add_accepted_status_to_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationprice',
            name='cost_sheet',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cost_sheet'),
        ),
        migrations.AddField(
            model_name='quotationprice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_prices', to='orders.order'),
        ),
    ]
