# Generated by Django 5.0 on 2025-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pv_prod_fab_col_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pv_sku_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pv_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='products_st_qty_in_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='products_st_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='variantsize',
            name='products_vs_var_size_idx',
        ),
    ]
